# Generated by Django 4.2.9 on 2024-05-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view',
            field=models.ImageField(blank=True, null=True, upload_to='item_view'),
        ),
    ]
